[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "i", "w" ]
run = "shell --confirm 'file -b --mime-type \"$0\" | grep -q \"^image/\" && wallset \"$0\" || echo \"Not an image\"' "
desc = "Set wallpaper"

