[default_session]
# startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "ğŸ™‚ Main"

[[session]]
name = "ğŸ“‚ Downloads"
path = "~/Downloads"
startup_command = "ll"

[[session]]
name = "ğŸ’¼ GPC"
path = "~/Projects/gpc"

[[session]]
name = "âŠ™ Dotfiles"
path = "~/dotfiles"
startup_command = "~/dotfiles/.config/sesh/dotfiles_startup_script.sh"

[[session]]
name = "ğŸ  Homelab"
path = "~/selfhosting"

[[session]]
name = "âŒ¨ï¸ Keyboard"
path = "~/Projects/my-keeb"
